name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Check Before Asking
      options:
        - label: Please check the issue list and confirm this bug is encountered for the first time.
          required: true
        - label: Please try full text in English and attach precise description.
          required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Please describe your environment details:
        - The version or commit id of this project.
        - Hardware parameters: operating system, compiler and CPU, etc.
        - Others
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Fast Reproduce Steps
      description: Please tell us how to reproduce this bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened? Picture is allowed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Other Information
      description: Please copy and paste any relevant log or other information.
    validations:
      required: false