name: Documentation Related
description: Suggest an improvement or report a bug for the documentation.
title: "[Doc]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: Through the [official website](https://www.oceanbase.com/docs/community), you can find all the documents about OceanBase.

  - type: checkboxes
    attributes:
      label: Check Before Asking
      options:
        - label: Please check the issue list and confirm this issue is encountered for the first time.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A description what error your find in our document, or what document we miss.

  - type: textarea
    attributes:
      label: Documentation Links
      description: Copy and paste one or more links of this documentation issue.

  - type: checkboxes
    attributes:
      label: Are you willing to submit a pull request?
      description: This is not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the improvement.
        We love to bring new contributors in.
      options:
        - label: Yes I am willing to submit a pull request.